# Generated by Django 5.2.5 on 2025-08-09 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_flowers_created_at_flowers_image_flowers_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.AddField(
            model_name='flowers',
            name='status',
            field=models.CharField(default='pending', max_length=16, null=True, verbose_name=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')]),
        ),
        migrations.AddField(
            model_name='flowers',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.category'),
        ),
    ]
