# Generated by Django 5.2.5 on 2025-08-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_category_flowers_status_flowers_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='price_after_discount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='flowers',
            name='price_before_discount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16, null=True),
        ),
    ]
