# Generated by Django 5.2.5 on 2025-08-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_flowers_price_after_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='color',
            field=models.CharField(choices=[('mavi', 'Mavi'), ('çehrayi', 'Çəhrayı'), ('qirmizi', 'Qırmızı'), ('sari', 'Sarı'), ('narıncı', 'Narıncı'), ('benovseyi', 'Bənövşəyi'), ('ag', 'Ağ'), ('mixed', 'Mixed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/flowers'),
        ),
    ]
