# Generated by Django 5.2.5 on 2025-08-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_flowers_expires_at_alter_flowers_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'expired')], default='pending', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
